### ISSUE TITLE
API Spec for Webcam

### ISSUE THREAD

**Issue by BK01** [BCDevExchange/Our-Project-Docs#103]
As the MOTI program owner, I want to engage the B.C. tech sector so I can build a webcam api that meets the needs of developers.

DOD
Create webcam swagger spec
Publish spec in repo with invitation to contribute
Update profile page with invitation to contribute and link to the repo

**Comment by BK01** [comment]
(Blocked) On hold until approval to build is received (Feb 2016?)

**Comment by karsmith** [comment]
Potential challenge to be used for Appathon March 3-4

**Comment by lmullane** [comment]
@f-w Can you please link this repo: https://github.com/bcgov/drivebc-webcam-api
to this profile page:
https://bcdevexchange.org/programs/Open511-DriveBC

**Comment by f-w** [comment]
@lmullane, done

**Comment by lmullane** [comment]
Thank you! @f-w

**Comment by lmullane** [comment]
This is complete: https://github.com/bcgov/drivebc-webcam-api
