### ISSUE TITLE
API List Page - Shorten API descriptions

### ISSUE THREAD

**Issue by BK01** [BCDevExchange/Our-Project-Docs#114]
#### _Story:_

As a developer I need access to a public tool that provides a searchable list of APIs with brief descriptive text (using a modern browser).
#### _Success Criteria:_
- More concise descriptive text
#### _Deliverables:_
-  Updated API List page in PROD with shortened 1-2 line descriptions.

**Comment by dbhume** [comment]
So that you can?

**Comment by lmullane** [comment]
@BK01 For the longer descriptions on the API console page, please make the links work.

**Comment by BK01** [comment]
Initial release to be published on Thursday Jan 14 for final review.
