### ISSUE TITLE
Question: is the resources page the only APIs / content that is available today?

### ISSUE THREAD

**Issue by bmann** [BCDevExchange/Our-Project-Docs#12]
Looking at the BCDevX site, I guess the resources page is the list of what is available -- https://bcdevexchange.org/#/resources

As I suggested in the HIVE meeting, perhaps we can use this issue queue to request / suggest data sets and APIs that people want access to. You can have a label called "data requests" so we can filter on that, and can have a "Looking for more APIs or data sets? Visit the issue queue to make your request" on that resources page that would link to that label here.

**Comment by kelpisland** [comment]
We are looking at a couple of options that will use either github "issues" or a markdown page or yaml to help build out the list by tapping into the community.

**Comment by ghost** [comment]
@kelpisland 
Is there an existing roadmap of data sets that will be opened up in the nearest future?
It wasn't quite clear at the meetup if there is one in the works already or it will be driven by demand from the public.

@bmann 
GitHub issues seems like a simple way to track data requests. They weren't necessarily designed for voting but we can just use a :+1: and do manual counts for now.

**Comment by kelpisland** [comment]
@yonderboi 
I'm not sure if there is a data set roadmap for existing request but it makes sense to me to post it as part of the [Data-requests repo](https://github.com/BCDevExchange/Data-Requests) (if it exists). I'll look into it and report back.

**Comment by bmann** [comment]
@kelpisland I really don't think you should split this into a gazillion different repos. Can we continue that discussion / re-open the issue you closed? https://github.com/BCDevExchange/Our-Project-Docs/issues/13

**Comment by kelpisland** [comment]
Sure - reopening [#13](https://github.com/BCDevExchange/Our-Project-Docs/issues/13)

**Comment by kelpisland** [comment]
Closing this issue:
We are moving forward with gitter to support collaboration discussions so look of the gitter badge where active dev (and chats) are happening
