### ISSUE TITLE
As a DevEx program owner I need have a f2f dialogue with the user community so that I can understand their needs and concerns regarding P4P

### ISSUE THREAD

**Issue by paulroberts68** [BCDevExchange/Our-Project-Docs#121]
Created by Peter/Paul

DOD
1. Prepare/Create GitHub Issues to discuss during event
Prepare scenarios we want to make sure to cover in discussions, for example:
-Multiple developers working on the same issue
-Incomplete Pull Request
2. Manage Invitations, Communications, Attendee Responses
3. Set Date & Secure Location
Our aim is to hold the event by the end of Feb 19. Suggestions:
-Vancouver: venue suggested or arranged by Boris
-Victoria: VIATEC
4. Invite developers
For Plan A, it was suggested that we try reaching out to Boris from Vancouver to participate and bring his contacts to this engagement. 
Plan B was to recruit a group from Victoria through other Meetup groups.

**Comment by mark-a-wilson** [comment]
@ragbay  and @lmullane have agreed on an agenda for the engagement session. I have a meeting with David H and Peter this afternoon and will run the plan by them, particularly the outcomes. Next steps: Secure Boris & small group of his contacts; set time & location.

**Comment by mark-a-wilson** [comment]
Hume and Peter's direction on the plan was that the focus needs to be much broader and more generative. We don't want the focus to be to poke holes in P4P, but to articulate the broader vision of the Exchange...We need to ask participants, "What is the value for you + what model(s) could facilitate those things? Where do we go from here?" 
- Participants: (Mark & Rommel to facilitate; Hume and Peter to articulate the vision + facilitate)
- Attendees:  Invite Boris and past contacts/participants ensuring we get a solid 20 attendees representing a good mixture of students, startups, hobbyist/freelancers, "big idea"/entrepreneur, civic-minded

Mark & Rommel working on a revised plan for the workshop.

**Comment by mark-a-wilson** [comment]
Next Steps:
1) Set date (David & Peter's availability)
2) Contact and confirm attendees
3) Find venue

**Comment by mark-a-wilson** [comment]
David & Peter will make themselves available. Aiming for week of Mar 7.

**Comment by mark-a-wilson** [comment]
@MeaghanRStewart , could you connect with @lmullane and get the details/contact for a venue that DevX has used before at **UBC Robson square**? Loren said the venue was very good. We're aiming to confirm a solid 20 participants. Could you contact the venue and see if they have availability on Mon, Tue, Wed, or Thu evening (March 7-10)?

**Comment by mark-a-wilson** [comment]
@lmullane , how can I get a complete list of contacts for all the Developers/entrepreneurs who have engaged so far from Vancouver?
