### ISSUE TITLE
Navigation Menu

### ISSUE THREAD

**Issue by pcrossley** [BCDevExchange/Our-Project-Docs#127]
As any persona visiting the website, I'd like to jump to content I'm looking for.

**Comment by pcrossley** [comment]
DOD: mapped navigation proposal based on current IA

**Comment by pcrossley** [comment]
1) Connect with @ragbay to discuss IA and usable options for navigation.

**Comment by f-w** [comment]
@pcrossley, is this issue at UX design stage or dev stage?

**Comment by pcrossley** [comment]
@f-w  IA discussion...no Dev yet, thanks.

**Comment by pcrossley** [comment]
@ragbay and I have discussed and touched base with @f-w:
Hamburger on left of page if possible - right side okay if tech reason.
"Sign-up" and "log in" to be persistent in header and not included in drop-down hamburger menu.
Hamburger menu has no label,
navigation elements within hamburger menu as follows:

Developers
  Code With Us
  API's
Entrepreneurs
  Partners
  API's
Public Sector 
  Partners
  Become a Partner
Blog
About Us

There is no "About Us" page yet, so this will be included once page exists.

**Comment by f-w** [comment]
![image](https://cloud.githubusercontent.com/assets/12823994/13821007/12f56d3c-eb5d-11e5-9379-b4801aa7a2e8.png)

**Comment by pcrossley** [comment]
"Developers" Link should point to:  https://bcdevexchange.org/home#developers-value-props
"Entrepreneurs" Link should point to: https://bcdevexchange.org/home#entrepreneurs-value-props
"Public Sector" Link should point to: https://bcdevexchange.org/home#public-sector-value-props

**Comment by pcrossley** [comment]
@ll911  - can you push the UAT ver of the menu to prod?
@paulroberts68  - we'll need to add a task to backlog to bring "blog" out of hamburger and place in persistent header.  Also, we'll need a task to write/create an "About Us" page and add that to the bottom of the drop-down hamburger menu.  Finally, on a mobile device, the "sign up" and "log in" labels wrap too much...we need to investigate a way to reduce the space the header consumes.  one thought might be to swap out the logo for a scaled-down version, so it doesn't take up so much room.

**Comment by f-w** [comment]
Added blog back to navbar. UAT is building...

**Comment by ll911** [comment]
@pcrossley @f-w can you confirm the hash you want to push to prod?

**Comment by f-w** [comment]
c6cf187. Wait for about 10min for UAT to finish building.

**Comment by ll911** [comment]
completed.
