### ISSUE TITLE
Data Request: land data from BC Assessment

### ISSUE THREAD

**Issue by bmann** [BCDevExchange/Our-Project-Docs#13]
(someone please edit this title and body, I'm adding it as an example data request)

Is there an API or other data available from BC Assessment? http://www.bcassessment.ca/

**Comment by kelpisland** [comment]
Hi bmann - we like the idea of using github for data request dialogue, I've started a new repo (https://github.com/BCDevExchange/Data-Requests) that is just an empty shell at this point but next week we'll look at adding a reasonable process getting the conversation started. Stay tuned!

**Comment by bmann** [comment]
I would not recommend spawning too many repos. 

If you want comments and pull requests on your docs, then centralize "community" issues here. 

But it's certainly a lot larger than just data requests.

Also, you said "we" -- it would be best if you can discuss in the open so we can see & participate in your thought process.

Please re-open for further discussion so others can see & contribute.

**Comment by kelpisland** [comment]
The idea behind a separate repo for data requests is rooted in the fact that those requests are managed by a distinct team of people who operate independently (but related to) the BCDevExchange. So from a "team" access and notifications point of view it make sense to separate it.
@bmann 
What's your thoughts about keeping the number of repos low?

**Comment by chenkirk** [comment]
@kelpisland I've opened another data request here:
https://github.com/BCDevExchange/Our-Project-Docs/issues/16

Not sure if you have decided to go with 2 repo or keep it all in one, so I've just initially created it here.

My 2 cents on more repo vs less repo: isn't the idea of open source so people who operate independently can come together and work on the same repository? :)

**Comment by kelpisland** [comment]
Closing this issue:
We are moving forward with glitter to support collaboration discussions so look of the gitter badge where active dev (and chats) are happening
