### ISSUE TITLE
Where is the master index of data sets? 

### ISSUE THREAD

**Issue by purecanuck** [BCDevExchange/Our-Project-Docs#14]
Where is the master list of data sets that we can choose from, to request access to?

**Comment by kelpisland** [comment]
I'm not sure what you mean - we are exploring a federated approach to presenting digital resources (including data) but at this point we don't have a plan for master data index. The priority we have is to design a method to present data, api's and project opportunities "in context" and from multiple sources.

**Comment by gndv** [comment]
@kelpisland, I think @purecanuck is referring to the point discussed at the Vancouver #BCDev event last week, that the development and startup community needs to have an idea of what kinds of data exist to know what to ask for. Basically - how would a non public servant get an idea the opportunities that may exist with data sets that aren't open yet. 

Maybe there needs to be an overview of the mayor types of information available? 

@purecanuck have you looked through http://www.data.gov.bc.ca/ ?

**Comment by chenkirk** [comment]
There's also a pretty cool list of public data here (not specific to BC) http://www.datasciencecentral.com/profiles/blogs/great-github-list-of-public-data-sets

**Comment by kelpisland** [comment]
@gndv , thanks for the clarification  - I think your suggestion for an overview of the major data sets a ministry/agency/etc has (open or not) would be, very much, a step in the right direction. Wondering how best to approach this in a useful way to link the data to the business context that would be better than just a simple list?

**Comment by kelpisland** [comment]
Closing this issue:
We are moving forward with gitter to support collaboration discussions so look of the gitter badge where active dev (and chats) are happening
