### ISSUE TITLE
Which municipal datasets are the best candidates for developing open data standards?

### ISSUE THREAD

**Issue by rwongmoon** [BCDevExchange/Our-Project-Docs#15]
Which municipal datasets would have the most value if made open and aggregated for regions in BC or even province/nation wide? Municipal government needs to know this in order to:
- build a business case for developing these standards
- focus their efforts on data that will provide the most benefit

For those of you who might not know, there are existing standards like Open311.org and Open511.org that include RESTful API specifications.  Do you think new data standards are the kind of development effort that BC Developer Exchange should facilitate?

Lastly, if municipal government did provide the most in-demand datasets in an agreed data standard, would you be willing to use the data and work with municipalities to help publicize your results?

**Comment by StormTide** [comment]
A common municipal financial presentation would be a huge win. I tried to seed one here: https://github.com/StormTide/Municipal-Finance but it didn't get very far.  The 'pitch' is that currently all the muni's make up their own financial statements. They follow no comparable accounting standard, not ifrs, xbrl or anything, and you cant even analyze the spending within a specific municipality year-to-year as they are known to change their accounting categorizations without providing any kind of mapping to the old methodology. Victoria for example is totally changing their statements this year, so you wont even be able to compare them to last year's. There are 13 muni's in greater Victoria, and not one can be compared to its neighbor on a financial basis, creating hilarious effects when it comes to talking about amalgamation. 

... so definitely a +1 to whether BCDevEx could help facilitate these types of standards, and a vote for starting with the bean counting.

**Comment by colgur** [comment]
Forgive the naive question: What kind of information do the municipalities share with the province? Is that information sharing obligatory?

**Comment by rwongmoon** [comment]
Hi colgur, that is a good question.  I wonder if there is an expert out there, maybe from provincial government, who could answer those questions?  I work for a municipality but I don't know the full extent of which data gets passed to the province.  I find that most municipalities function in practice as a loosely federated set of separate businesses operating within the same jurisdiction.  In my experience, each department or "line of business" will handle that information exchange separately - then there's a further team that is trying to "discover" data and provide it to their Open Data Catalogue ;)

Out of interest I went to the province's Data BC catalogue (http://catalogue.data.gov.bc.ca), searched for "municipal" and got 202 datasets.  This included a fair amount of historical financial data, interestingly enough, although it is probably overly summarized for StormTide's requirements.  I know a few examples of efforts to consolidate municipal data to a provincial level - one is ICIS (http://www.icisociety.ca) which consolidates land parcel and addressing geospatial data from "members" which include municipal governments.  Another is DriveBC (http://www.drivebc.ca/) which gathers road condition and event information, run by the Ministry of Transportation and Infrastructure.  They are actively trying to promote municipalities providing this type of data from their jurisdictions (non major road networks) using the Open511 standard.  I'm not a spokesperson for either of these so my apologies if the descriptions fall short.  And I don't think either of these are obligatory, but are highly encouraged.

**Comment by kelpisland** [comment]
Closing this issue:
We are moving forward with gitter to support collaboration discussions so look of the gitter badge where active dev (and chats) are happening
