### ISSUE TITLE
Data Request: campground data from BC Parks

### ISSUE THREAD

**Issue by chenkirk** [BCDevExchange/Our-Project-Docs#16]
http://www.env.gov.bc.ca/bcparks/

Is there an API or other data available to access information about BC camp sites, trails, and parks?

**Comment by lmullane** [comment]
Hi Chen,

Thanks for contacting us. Currently, we do not have a API with vector points for parks, trails, and campsites.

However, the locations of BC Parks are available for download from the DataBC Catalogue under the Open Government License (OGL) – British Columbia:
http://catalogue.data.gov.bc.ca/dataset/bc-parks-ecological-reserves-and-protected-areas

Where trail location data exists, it will be in the Recreation Lines data, which is also available for download from the DataBC Catalogue under the Open Government License – British Columbia:
http://catalogue.data.gov.bc.ca/dataset/recreation-line 

There are also a number of data layers under the OGL, related to campsite locations: http://catalogue.data.gov.bc.ca/dataset?license_id=2&q=campsite 

We have a web map service which give a raster image (no vector points) of BC park locations and trails. You can find the Parks, Recreation and Tourism WMS and guides on how to make a persistent connection here: http://www.data.gov.bc.ca/dbc/geographic/connect/index.page?

The caveat is content from the web map service is under Crown Copyright so it’s use is more restricted. 

Can you tell us more about how you plan to use it? The reason I ask is that the park data does not change often, which may be a consideration for what you are building.

Cheers,

Loren
