### ISSUE TITLE
Update Collection Notice For Gitter

### ISSUE THREAD

**Issue by kelpisland** [BCDevExchange/Our-Project-Docs#34]
The mouse over "notice" for Gitter.io needs to be refined.

**Comment by DavidR8** [comment]
I have revised language from the Privacy Branch. Awaiting approval from David Hume

**Comment by DavidR8** [comment]
Revised collection notice language has been approved as follows:

Please do not provide any personal information or third-party personal information (ie. talk about others) in your use of the Gitter application. Any information you choose to provide will not be in the custody or control of the Ministry of Advanced Education. For more information, please see the Privacy Policy of Gitter.

**Comment by kelpisland** [comment]
I've added it to the docs repo gitter button, I'll include the txt as a template reference in the sample read.md for future users.
