### ISSUE TITLE
New API for console

### ISSUE THREAD

**Issue by lmullane** [BCDevExchange/Our-Project-Docs#35]
Add Surrey Service Request API: http://cosmos.surrey.ca/api/open311/discovery.xml

**Comment by ll911** [comment]
o   Draft complete: City of Surrey API console and associated swagger v1.2 definition in WSO2.
o   Next: present to Surrey on Friday -> UAT -> refinements -> republish next week.

https://api.bcdevexchange.org/apim/store/apis/info?name=surrey-open311&version=2&provider=admin

**Comment by BK01** [comment]
First iteration complete and published. Next sprint - additional feedback, client UAT, refinements and re-publication with version 2.
