### ISSUE TITLE
Create the Engagement Wordpress Profile Page

### ISSUE THREAD

**Issue by kelpisland** [BCDevExchange/Our-Project-Docs#36]
As a program owner I need to create a profile page for Engagement WordPress instance so that I can collaborate with other innovators to improve the services this engagement site provides.

Created by: David Hume

DOD:
1. Ensure provenance  
2. Create draft content for all profile page sections
3. Be ready to send for final review and decision

Approach:

Connect with:
David Hume, Justin Hewitt, David Wrate, Todd Wilson.

**Comment by paulroberts68** [comment]
Conducting some background work to confirm the application provenance. I've ascertained that only one contractor (from CGI) has produced code fort he core WordPress application.

**Comment by DavidR8** [comment]
A security review of the code is also required prior to release.

**Comment by lmullane** [comment]
@dy2288 Can you please create a profile page for the Citizen Engagement with full features. Once complete please reassign to @DavidR8.

**Comment by dy2288** [comment]
Done: programs/Citizen%20Engagement%20Web%20Toolkit.

**Comment by lmullane** [comment]
@dy2288 Can you please link to this repo: https://github.com/bcgov/citizen-engagement-web-toolkit Thanks!

**Comment by lmullane** [comment]
@dy2288 Could you also please give @SteveMHoward edit powers to the profile page:) @DavidR8

**Comment by dy2288** [comment]
I've added the Github URL and the editor to the list, however it seems like Steve isn't able to edit any content. @f-w, anything I'm doing wrong as far as you can see? Or is this a bug?

**Comment by f-w** [comment]
@dy2288, you need to create an "editors" property of array type to the profile object. Add Steve's acct id to editors.

**Comment by dy2288** [comment]
Access granted (not a bug). MongoVUE was reporting that the record for "editors" was overwritten, but actually just deleted it...

**Comment by pcrossley** [comment]
waiting on feedback to then finalize

**Comment by DavidR8** [comment]
Need to decide if pics are required for profile page

**Comment by lmullane** [comment]
@f-w Please hide the Work With Us section on this page. @DavidR8
https://bcdevexchange.org/programs/Citizen%20Engagement%20Web%20Toolkit

**Comment by f-w** [comment]
@lmullane, work with us is hidden. Back to you.
