### ISSUE TITLE
Create a glossary for project aconyms

### ISSUE THREAD

**Issue by StormTide** [BCDevExchange/Our-Project-Docs#39]
Trying to follow what you guys are posting from a developer's perspective, but not keeping up with the internal code-names being used... PRAD1K etc... Can we add a glossary/definition list or use expanded forms.

**Comment by kelpisland** [comment]
Apologies: it's easy to forget that we're so jargon heavy in our day to day work - and we're really happy you are following along, that's the whole reason we're moving to GH Issues.  A glossary is an awesome idea! I'll get one started and post the link - stay tuned.
