### ISSUE TITLE
Metrics and Analytics

### ISSUE THREAD

**Issue by dy2288** [BCDevExchange/Our-Project-Docs#41]
<a rel="Exploration" href="https://github.com/BCDevExchange/docs/blob/master/discussion/projectstates.md"><img alt="Being designed and built, but in the lab. May change, disappear, or be buggy." style="border-width:0" src="http://bcdevexchange.org/badge/2.svg" title="Being designed and built, but in the lab. May change, disappear, or be buggy." /></a>
# Story:

As a BCDevExchange program owner I need to see a page that contains important statistics regarding the exchange so that I can make business decision regarding product features.
# Additional details:
- Historical data is important (i.e. having graphs that identify trends over time).
- The report should be dynamic if possible.
- PRAD 1K usage and/or Github usage will be preferable. In preperation for this, we should gather  Github trends related to each profile page if possible.

Links:

[Draft Numbers page](https://bcdevexchange.org/numbers)
# Success criteria:
1. Extending our ability to track events in Google Analytics: Creating goals, tracking clicks, ensuring SPAM data is not tracked, extracting useful data and sharing it with Product Managers.
2. Exploring tracking Github events (push, pull, time to close, etc) in a BCDevX context
# Deliverables:
- [x] List and/or dashboard of important stats, trends and events we want to track.
- [x] Cleaner Google Analytics data (excluding SPAM, internal traffic?).
- [x] More meaningful tracking in Google Analytics (what do people click in a Profile page?)
# Approach:
- [x] Evaluate current metrics
- [x] Define requirements and important stats/trends
- [x] Gap analysis (what is missing that we don't already have?)
- [x] Evaluate feasability of tracking (e.g. does Github expose certain metrics?)
- [x] Modify analytics code to track missing events.
# Connect with:
- Loren M
- Peter W
- Todd W

**Comment by dy2288** [comment]
@kelpisland - do we have Webmaster Tools configured so we can get more information about the site's visibility in Google search results?

**Comment by dy2288** [comment]
Draft

**Comment by kelpisland** [comment]
I'm not sure what's set up. We do have a Google Analytics live. You are set up with admin privileges with your gmail address.

**Comment by kelpisland** [comment]
Looks like it was set up:

![screen shot 2015-09-23 at 4 25 07 pm](https://cloud.githubusercontent.com/assets/9368818/10061701/176264e6-6210-11e5-8c0c-0b6dc0bb679e.png)

**Comment by dy2288** [comment]
Important questions:
- Do people use the profile pages? How? [Partial, to be improved]
- Do people sign-up? [Missing, Possible with Dev effort]
- How many people log in? [Missing, Possible]
- How are our Github pages performing for each profile page? [Missing, Possible with Dev effort = Github API + stored procedure + feeding into GA?]
- Do visitors find the resources they need via profile pages? [Missing, Possible with Click Tracking](i.e. Github, external resources, etc), example:
  Profile -> Resources -> Github
  Profile -> Resources -> API Hub
  Profile -> Resources -> Waffle.io

Github statistics: [Missing, Possible with Dev effort + Github API]
- Do people submit pull requests? How many?
- Do people create issues? How many?
- Commit / week or commit / day average?
- Fork, star, watch statistics
