### ISSUE TITLE
Swagger version update (2.0)

### ISSUE THREAD

**Issue by BK01** [BCDevExchange/Our-Project-Docs#43]
Swagger 1.2 -> 2.0

**Comment by BK01** [comment]
Update swagger definitions from version 1.2 to 2.0. This will allow us to continue to offer API consoles in the latest API explorer software.

**Comment by kelpisland** [comment]
Is this a requirement for our WSO2 experiment?

**Comment by BK01** [comment]
Correct. The swagger 2.0 conversion is required to test the API console function within Swagger Editor and Mashape Gelato. Swagger 2.0 is also used in future versions of WSO2 (1.9+).

---

Brian Kelsey | DataBC

**Comment by BK01** [comment]
Story:

I need to be able to utilize Swagger definition files in different versions of API explorers. I need to ensure that the definition files are portable and reflect current standards.

Success Criteria:
- Updated Swagger definition files (v1.2 -> v2.0)

Deliverables:
- Swagger definition files (for existing API consoles) converted from version 1.2 to version 2.0 (BCDataCatalogue, BCLaws, Geocoder, KamloopsGarbagePickup, Open511, Surrey-open311)

**Comment by BK01** [comment]
Swagger definitions updated for the following API consoles: BCDataCatalogue, BCLaws, KamloopsGarbagePickup, Open511, Surrey-open311.

Swagger definition conversion underway for the following APIs: Geocoder
