### ISSUE TITLE
Langley - Cemetery API added to console

### ISSUE THREAD

**Issue by lmullane** [BCDevExchange/Our-Project-Docs#46]
Township of Langley

**Comment by lmullane** [comment]
We need to create a Swagger Definition and add a new APIto the console.

**Comment by BK01** [comment]
Who is the API owner and primary contact?

**Comment by BK01** [comment]
Story:

As a developer I need to understand how the cemetery API (Township of Langley) works. I need to be able to explore the resources and parameters available in the API.

Success Criteria:
- Approval from the Township of Langley to build a public API console
- Functional API console in the API store for the cemetery API

Deliverables:
- Swagger definition file (v1.2) completed
- Published API console in current API store (WSO2) - version 1

**Comment by BK01** [comment]
API console has been published to the API store. Compatibility issues are being experienced between WSO2 and Socrata. A ticket has been submitted with Socrata to investigate the issue. Resolution is not anticipated within this sprint.

Current efforts moving to researching other options.

**Comment by BK01** [comment]
Simulated API console successfully tested in Swagger editor, using Swagger v2.0 definition. 
https://uat.bcdevexchange.org/swagger-editor
