### ISSUE TITLE
Review profile page analytics with profile/page owners

### ISSUE THREAD

**Issue by paulroberts68** [BCDevExchange/Our-Project-Docs#52]
As a developer I need to know what program owners need to see on their analytic dashboard so that I can configure it to show the appropriate amount and type of data.

Created by: Daniel

DOD
1. Engage with the appropriate number of clients and determine what content we need to provide.

Approach:

Connect with:
Loren, Rommel

**Comment by dy2288** [comment]
@lmullane & @ragbay I'm going to connect with you two to pass on this work to you since you have access to the various program owners. I'll show you my progress and walk you through a demo.

**Comment by pcrossley** [comment]
look at including a question in interview script

**Comment by lmullane** [comment]
@pcrossley we interviewed 2 program owners.
