### ISSUE TITLE
As a user I want to be able to reserve a specialized lab URL name so that I can prove that the work I am doing is under the safe net of the exchange lab construct.

### ISSUE THREAD

**Issue by paulroberts68** [BCDevExchange/Our-Project-Docs#53]
As a user I want to be able to reserve a specialized lab URL name so that I can prove that the work I am doing is under the safe net of the exchange lab construct.

Created by: Peter

DOD
Back end workflow (via email to our techs?)
Tested / verified against AZURE, AWS?
Management console by user/ org/user for adding/changing/deleting reserved names

**Comment by f-w** [comment]
Are all devx registered users allowed to reserve names or restricted to verified program owner? I think it's the latter since my understanding is that eventually lab will either be charge allocated or limited capacity computing resource.

**Comment by watkinspd** [comment]
Intended users will be public sector clients of the exchange. Idea is to help public sector clients to collaborate with developers through the "labs" construct.

**Comment by f-w** [comment]
How to identify public section clients? By hand pick, by GitHub authenticated email address domain, or something else? If by email domain, I need a pre-defined list as I assume it's not limited to gov.bc.ca.

**Comment by f-w** [comment]
Resolution: starting with handpick from existing authorized profile editors.

**Comment by f-w** [comment]
Some of the features can be combined with BCDevExchange/BCDevExchange-app/issues/158

**Comment by pcrossley** [comment]
What's the sense on the size of this undertaking?
