### ISSUE TITLE
Create the legal terms for PRAD 1K

### ISSUE THREAD

**Issue by paulroberts68** [BCDevExchange/Our-Project-Docs#54]
As a program owner I need to ensure that participants in the exchange agree to legal terms so that PRAD 1K can be initiated.

Created by: Peter/Hume

DOD
1. Complete all 4 sets of legal terms.
2. Attain legal sign-off
3. Attain OCG sign-off
4. Align the terms with those of the framework of exchange terms

Approach

Connect with

**Comment by DavidR8** [comment]
Draft Pay for Pull terms sent to Legal

**Comment by DavidR8** [comment]
@leslieanderson Note Terms must accommodate multiple submissions (taken from ticket #68)

**Comment by pcrossley** [comment]
Am I correct in understanding that the legal terms have been created, they're just waiting on legal?  If so, we can mark this as done and create another for "legal sign-off of Prad1K terms"

**Comment by DavidR8** [comment]
@pcrossley Yes that makes sense as we have draft terms from Legal Services. We will return our feedback today/tomorrow in time for a Thursday meeting (to be confirmed) cc/ @leslieanderson
