### ISSUE TITLE
Identify early adopters for PRAD 1K

### ISSUE THREAD

**Issue by paulroberts68** [BCDevExchange/Our-Project-Docs#57]
As a program owner I need to identify 3 early adopter who can help the team with testing PRAD 1K

**Comment by lmullane** [comment]
@MeaghanRStewart Could you please email @paulroberts68 the account slide deck with the goals table. Thanks!

**Comment by MeaghanRStewart** [comment]
Currently Blair has the updated copy, I will request it from him.

**Comment by DavidR8** [comment]
@paulroberts68 suggest early adopters are Citizen Engagement, Geocoder, Environmental Reporting, Queens Printer.
Moving to "Done"
cc/ @lmullane @MeghanRStewart
