### ISSUE TITLE
Finalize Langley Profile Page

### ISSUE THREAD

**Issue by kelpisland** [BCDevExchange/Our-Project-Docs#58]
DOD
Publish Langley profile page.

Approach

Connect with
Steve Scheepmaker
Loren

**Comment by DavidR8** [comment]
Sent email to Steve Scheepmaker to discuss licensing.

**Comment by pcrossley** [comment]
thanks

**Comment by ragbay** [comment]
thanks (testing)

**Comment by DavidR8** [comment]
Call booked for 11am Oct 21

**Comment by DavidR8** [comment]
Steve is taking Apache license recommendation to his legal team. Does not expect an issue.

**Comment by DavidR8** [comment]
Steve advised waiting on approvals from Legal. Not going to happen for this Sprint. Will be good to go when approvals received.

**Comment by lmullane** [comment]
@f-w Could you please remove the GitHub links, counter, etc. from this page:
https://bcdevexchange.org/programs/Langley Thanks in advance.

**Comment by f-w** [comment]
@lmullane, done.

**Comment by lmullane** [comment]
Thank you, @f-w !

**Comment by lmullane** [comment]
@f-w could you please rename this page from: https://bcdevexchange.org/programs/Langley

To:
https://bcdevexchange.org/programs/Township of Langley

**Comment by f-w** [comment]
@lmullane, you can rename it in yaml file now.

**Comment by lmullane** [comment]
Thanks, @f-w
