### ISSUE TITLE
Suggestion / Question: wiki docs are not commentable / editable - put it into the repo directly?

### ISSUE THREAD

**Issue by bmann** [BCDevExchange/Our-Project-Docs#6]
Great to see this up on GitHub! Welcome and congratulations.

A suggestion / question. Currently, there is lots of info in the wiki. I have lots of questions about the docs. There doesn't currently seem to be a way to make comments.

A suggestion: you might want to check in the wiki as markdown documents (including images that you've currently uploaded in issues). Then, us outside developers can fork it and make pull requests and/or open issues against portions of the docs themselves.

You could also publish the whole thing as a website using the Github Pages functionality.

**Comment by kelpisland** [comment]
Thanks for the suggestion - we are really keen on feedback so yes, I agree it's a good idea to set up the wiki files as MD for easy comments. Stay tuned for the changes.

**Comment by kelpisland** [comment]
I've added a user story to our backlog so we can devote some time to this in an upcoming sprint.

**Comment by GregTurner** [comment]
+1

**Comment by AlexWhiteIncorporated** [comment]
Good suggestion. We've moved content from the docs/wiki to docs/discussion to better enable feedback and discussion. 

Thanks!
