### ISSUE TITLE
Organize a co-design session with BCA to create their Profile Page

### ISSUE THREAD

**Issue by kelpisland** [BCDevExchange/Our-Project-Docs#60]
Story:
As BCA, I need to draft launch documentation, and receive GitHub training in preparation for launch.

Issues:
Docs Needed?
*Communicate constraints
*Use Cases & Templates
*Profile Page Draft
*Communications Plan
*Dhume needs to contact/arrange meeting with BCA

Approach:
*Meaghan to coordinate next steps/llist working with Loren
*Under direction from Loren (Meaghan)
*Docs drafted by DH, Sabrina, Joel, Loren
*Todd to connect with Jack on GitHub Training

DOD
1. Output of this exercise will be to create a wire frame of the content.
2.Review with David or Peter (if they weren't part of the co-design session) and approved for release.
3. Release into production.

Approach

Connect with
Peter, David H, Loren, Todd

**Comment by lmullane** [comment]
@dbhume When you have time let's connect on next steps.

**Comment by pcrossley** [comment]
Who is accountable to drive key dates? (warm handoff from Blair to Meaghan?)

**Comment by MeaghanRStewart** [comment]
@pcrossley , Meaghan will work with the account managers to ensure that key deliverables are met. By key dates are you referring to overall account goals or sprint tasks?

**Comment by pcrossley** [comment]
@MeaghanRStewart,  I've just transcribed what you (I think) had written on the Post-It during Sprint Planning.  Maybe Blair knows?

**Comment by lmullane** [comment]
This is being reviewed.
