### ISSUE TITLE
Create a BCDevExchange profile page

### ISSUE THREAD

**Issue by kelpisland** [BCDevExchange/Our-Project-Docs#61]
<a rel="Exploration" href="https://github.com/BCDevExchange/docs/blob/master/discussion/projectstates.md"><img alt="Being designed and built, but in the lab. May change, disappear, or be buggy." style="border-width:0" src="http://bcdevexchange.org/badge/2.svg" title="Being designed and built, but in the lab. May change, disappear, or be buggy." /></a>  
# Story:

As the BCDevExchange program owner, I need a profile page.
# Success criteria:
1. Profile page in produced
2. Linked to GitHub repo

**Comment by lmullane** [comment]
@dy2288 Could you please create a profile page with all the features for the BCDevExchange and then assign this ticket back to me. Much thanks.

**Comment by dy2288** [comment]
https://uat.bcdevexchange.org/programs/BCDevExchange

**Comment by lmullane** [comment]
Page is with program owners for review.

**Comment by MeaghanRStewart** [comment]
Once draft has been reviewed and approved, can be placed into production and marked as "Done".  Is this a correct assumption @lmullane ?

**Comment by lmullane** [comment]
That’s correct.

**Comment by lmullane** [comment]
Working to arrange photos.

**Comment by lmullane** [comment]
@dbhume https://uat.bcdevexchange.org/programs/BCDevExchange

**Comment by lmullane** [comment]
Photos have been taken, but may not be edited by end of sprint.
