### ISSUE TITLE
Public sector sign-up prototype and user testing

### ISSUE THREAD

**Issue by lmullane** [BCDevExchange/Our-Project-Docs#64]
As a public sector program owner, I want to sign up to the BCDevExchange and publish a profile page.

DOD:
- confirm journey map
- Develop prototype
- recruit program owners
- test and report out

**Comment by pcrossley** [comment]
@paulroberts68 What's the priority of this one?

**Comment by lmullane** [comment]
We have 2 more user test to complete, followed by reporting out.
