### ISSUE TITLE
Profile page owner can accept more than 1 pull request

### ISSUE THREAD

**Issue by paulroberts68** [BCDevExchange/Our-Project-Docs#68]
As a profile page owner I need to be able to the accept more than 1 pull request during a PRAD 1K transaction cycle so that I can access all the good code available.

**Comment by paulroberts68** [comment]
@kelpisland Do you and Leslie have time to complete this story in Sprint 14 (along with the other PRAD 1K stuff?)

**Comment by DavidR8** [comment]
@paulroberts68 @kelpisland
We can adjust the terms as necessary; is this more of a github functionality ticket?

**Comment by DavidR8** [comment]
Incorporated into #54
