### ISSUE TITLE
API Store Upgrade Estimate

### ISSUE THREAD

**Issue by BK01** [BCDevExchange/Our-Project-Docs#70]
#### _Story:_

As a developer I need access to a public tool to explore and understand how APIs function. I need to be able to explore the resources and parameters available in each API using a modern browser.
#### _Success Criteria:_
- Agreement and documentation on a list of tasks required to complete the work.
- An estimate of time to complete the work based on technical steps and available resources. 
- Proposed plan to complete the tasks
- Leverage modular architecture for API store functions
#### _Deliverables:_
-  Retire the current API store (https://api.bcdevexchange.org/apim/store/)
-  Implement a new API store
-  Re-build all API consoles listed in the current API store
-  Build and configure new supporting technology to allow API consoles to function.
#### _Sub-tasks:_
-  Describe current state of the API Store
-  Describe future state of the API Store (technology suite)
-  Describe steps to retire the current API store
-  Describe steps to implement and configure future state API store
-  Describe steps to implement API consoles
-  Describe API owner role and requirements to participate in API store (pub url)
-  Record time and resource estimate to complete the steps described above (in a future sprint)

**Comment by pcrossley** [comment]
As of Nov 24 BK is on vacation until Nov 26.  So this is not in-progress.  If it's actually assigned elsewhere, please update assignee.
