### ISSUE TITLE
BCA API Spec Design

### ISSUE THREAD

**Issue by paulroberts68** [BCDevExchange/Our-Project-Docs#76]
As a BCA program owner I want to create an API spec that I can use to collaborate with developers.

Created by Peter

DOD
1. Create API design
2. Determine collaboration tool as per Fred`s design.

Connect with
Fred, Todd, Peter, David H

**Comment by f-w** [comment]
@MeaghanRStewart, time to have a discovery session with client

**Comment by kelpisland** [comment]
The BCA repo is set up and they are ready to rock
