### ISSUE TITLE
Suggestion: I think the Red Research badge would be better as a Blue (sky) Ideation badge

### ISSUE THREAD

**Issue by watkinspd** [BCDevExchange/Our-Project-Docs#8]
Suggested changes can be viewed at my forked version of the repo.

https://github.com/watkinspd/docs/blob/master/discussion/projectstates.md

https://github.com/watkinspd/docs/blob/master/discussion/statelabels.md

**Comment by GregTurner** [comment]
I glad the badges are a hit. If were going to seriously use them is
delivery scenarios, I'd like to change how they are linked. E,g. Not static
from shields.io.

**Comment by AlexWhiteIncorporated** [comment]
I like the blue, and it seems like "Ideation" is a real word, so could work. Other suggested ideas were "Experimental" and "Exploration" (from Andy at MoE). All would work for me.

FYI - The changes you made to the non-badge labels (Icons, Letters, small banners, large banners) for the Research items broke the links (they were referencing .png files in the docs/images folder). These may get scrapped anyways (they were an early stage idea), though I think we might want something that works for physical documents, which also contains the description / definition of the state (like, this document is Research / Ideation, and that means xyz). That's the requirement the large banner was trying to meet.

**Comment by AlexWhiteIncorporated** [comment]
Some further discussions have brought up another front runner suggestion - "Inspiration". Please weigh in with your thoughts.

"Inspiration"?

"Exploration"?

I think I vote for exploration.

**Comment by watkinspd** [comment]
You can see what Inspiration looks like on my fork of the repo.

**Comment by kelpisland** [comment]
After a frenzied white board session we've got 3 new frontrunners:
Inspiration
Exploration
Adoption

**Comment by AlexWhiteIncorporated** [comment]
New badges adopted!
