### ISSUE TITLE
Publish profile page for the City of Victoria

### ISSUE THREAD

**Issue by MeaghanRStewart** [BCDevExchange/Our-Project-Docs#87]
As a program owner for Victoria city I need to create a profile page so that I can access the DevEx services. Connected to ticket #73

Created by Meaghan

DOD
1. Submitted for review to City Executive
2. Approved for posting to BC Dev Exchange site

Connect with 

Loren, Peter, David W.

**Comment by lmullane** [comment]
@dy2288 Can you please create a profile page for the City of Victoria.

**Comment by dy2288** [comment]
City of Victoria now available.

**Comment by pcrossley** [comment]
Sounds like this is done, according to DY comment...
