### ISSUE TITLE
As a program owner I want to test PRAD 1K with some early adopters to test the UX experience so that I can determine what an MVP will look like.

### ISSUE THREAD

**Issue by paulroberts68** [BCDevExchange/Our-Project-Docs#91]
Early UX research has identified some potential collision points in the pay for pull process. Work has been conducted to anticipate and alleviate some areas of potential confusion but further research needs to be conducted using a simulated realistic scenario.  

Created by: Peter/Paul

DOD
Test with up to three developers

Connect with Paul/Peter

**Comment by pcrossley** [comment]
unassigned and unestimated, therefore not in progress.  If assignee is known, please update accordingly.  Not listed in any bull's-eye(?)

**Comment by kelpisland** [comment]
This is the crucible test - @paulroberts68 is arranging contract. Dev will work on BClaws issue.
