### ISSUE TITLE
Publish BCDevExchange Profile Page

### ISSUE THREAD

**Issue by pcrossley** [BCDevExchange/Our-Project-Docs#94]
related to #61.#61 sees the page created.
this ticket is done when profile page is pushed to prod (therefore 'approved').

**Comment by lmullane** [comment]
@dy2288 This is approved. Please add this page to the YAML.
https://bcdevexchange.org/programs/BCDevExchange

**Comment by lmullane** [comment]
@dy2288 And this one to please:  https://bcdevexchange.org/programs/Citizen%20Engagement%20Web%20Toolkit
