### ISSUE TITLE
As a MOTI program owner I want to have built the first iteration of my API so that developers can use build against it during the March hackathon.

### ISSUE THREAD

**Issue by karsmith** [BCDevExchange/Our-Project-Docs#98]
Develop API code for web cam app which can be listed as a resource on the profile page.

Created by Peter

DOD
1. A functioning API that has been build IAW the spec - COMPLETE in Dec 2015
2. API link displayed on the profile page - COMPLETE
3. API listed - BLOCKED

Connect with Peter, Todd

**Comment by f-w** [comment]
@ll911 , Does api.bcdevexchange.org contain (unpublished?) webcam API spec? I only found open511.

**Comment by ll911** [comment]
@f-w the bcgov API swagger staged in BCDC for unpublished content.

**Comment by BK01** [comment]
Will initiate work this week to create an API console for the webcam API (using existing swagger definition, against existing API). This API console will be listed in the BCDevX API list. 

Related items:
- Confirmation on existence of associated profile page
- Confirmation from API owner on approved API console release date

**Comment by BK01** [comment]
BC Highway Cam - CSV file [OGL] - In progress/on track for announcement date

BC Highway Cam - API Spec [Swagger file] - Complete in Dec 2015, awaiting approvals/direction on next steps / license.

**Comment by BK01** [comment]
BC Highway Cam - CSV file [OGL] - COMPLETE - PUBLISHED
BC Highway Cam - Swagger - COMPLETE - ON GITHUB
BC Highway Cam - API Console - Requires MOTI approval AND a metadata record (with checklist and license) in the BC Data Catalogue. Following this, an API console can be added to the BCDevX API List.

**Comment by BK01** [comment]
Proposal for next sprint - Create the new API List page entry, URL and descriptive text ahead of time. Store offline, if approved in April, introduce new entry to API List page via GitHub.

Risk statement - API List  update (for webcams) must not be released prior to approval from TRAN
